-- show databases;
-- create database if not exists connection character set utf8 collate utf8_general_ci;
-- show databases;
-- drop database if exists connection;
-- show databases;
-- create database if not exists connection character set utf8 collate utf8_general_ci;
-- select default_character_set_name, default_collation_name from information_schema.schemata where schema_name = 'connection';
-- alter database connection character set utf8mb4 collate utf8mb4_general_ci;
-- select default_character_set_name, default_collation_name from information_schema.schemata where schema_name = 'connection';